### ISSUE TITLE
Selecting 'View' generates 404 message

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#10]
Currently, even when there is no Development Plan document to be viewed, there is an active 'View' link. And when the link is selected, a 404 message is displayed.

Recommendation is that if there is no document available, then do not have an active 'View' link.

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21659725/14845148-d29a-11e6-9eea-6c4ac49da1ee.png)

**Comment by justingreco** [comment]
It is not possible for us to know if there is a document or not since the document is manually added to the City website.
