### ISSUE TITLE
Search needs to ability to deselect Between and Within parameters

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#11]
The search feature in the left frame needs to have the ability to de-select the Between/calendar search parameter and the Within/location search parameter, in the same way the Status can be de-selected. Otherwise, even if that information is not known or the user does not want Between/calendar or Within/location to be included in the search, it will automatically be included because it can’t be excluded.

**Comment by justingreco** [comment]
We do not want the users to not have a date range since there is a limit of the number of features that can be returned.  Since there are hundreds of thousands of permits, showing all the data would not be possible.

**Comment by chavisa** [comment]
To control the amount of data displayed, when the application is started, then the default should be:
The data table default should be no data rows displayed
 - None of the boxed should checked for Permits or Development Plans (Currently all boxes are checked for each)
 - The calendar should default to the current date, for both the start and end day (Current default is current date and 1 year previous to the current date)
 - The With/location should default to 1/4 mile (Current default is All)

**Comment by justingreco** [comment]
Development services wanted there to be data when the application loaded.  Also they wanted the default time range for the Development Plans to be 1 year.  Also we don't want the user have to set all of these.
