### ISSUE TITLE
The table data is displayed incorrrectly by Status

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#13]
Status has 5 options which can be selected individually or as a collective group. If all 5 are selected, then the data for all 5 are displayed in the table. As each option is deselected, then the data for that option is no longer displayed. Which means that if all options are deselected, then no data should be displayed in the table. But instead when no options are selected all data is still displayed, the same as if all options were selected.
This should be changed so that when no options are selected, then no data is displayed.

**Comment by justingreco** [comment]
Fixed so that when no options are selected, nothing is displayed in the table.
