### ISSUE TITLE
Table data is too wide for the screen

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#14]
On a laptop, when the table data is displayed, the user has to scroll right to locate the vertical scroll bar to scroll down. With the amount of data being displayed, on a laptop, the user cannot see all of the data in a single row without having to scroll back and forth, horizontally. If the menu frame had a toggle that would allow it to be hidden/collapsed & displayed (like the table data) it would be much more user friendly - for laptop users.

**Comment by justingreco** [comment]
Is this for a certain browser?  I do not see this on my end, but I am on a Mac and not using IE.

**Comment by chavisa** [comment]
This is for all browsers. My laptop has a 13 inch screen (as do probably a lost of user's laptops) and I think that is the issue.  The amount of data in each row simply doesn't fit.

**Comment by justingreco** [comment]
I cant replicate this on my computer, even with the browser window simulating a 13" laptop screen.
