### ISSUE TITLE
IS the calendar for Submitted Date, Approved Date or some other date

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#17]
On the table there is an 'Approved Date' and a 'Submitted Date'. The assumption is that the calendar will allow a search to be done  by one of those dates. So, is the calendar for the Approved Date, the Submitted Date or neither.

The calendar should indicate what specific date it refers to.

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21725850/1eb4e1ae-d408-11e6-9435-25a4be7f24aa.png)

**Comment by justingreco** [comment]
Labeled "Date Submitted Range"
