### ISSUE TITLE
The Info Sheet displayed does not always correspond to the row selected

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#19]
I refer to the Information Sheet (see below) as the display which contains the Plan #,  Plan Name, Plan Type, etc and is displayed when the Marker is clicked.

The assumption is that when a row in the table is selected, the corresponding Marker will be located and the Info Sheet for that Marker will be displayed, if it is available. And If another row is selected, the same process will be repeated - the new Marker will be located and the corresponding Info Sheet will be displayed.

What is occurring currently is the first Info Sheet is displaying correctly, but when the next row is selected, the Info Sheet for that marker does not display. The previous Info Sheet continues to be displayed. 

For example, I selected a row for Plan # S-47-2016 and displayed the Info Sheet, then I scrolled and selected the data row for Plan # S-17-2016. The Info Sheet for Plan S-17-2016 did not display and the Info Sheet for Plan # S-47-2016 continued to be displayed. (See attached below).

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21728223/16c73842-d413-11e6-89b4-55ef00ebb469.png)

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21728749/d36b5936-d415-11e6-86ba-7a96e6b8adfc.png)

**Comment by justingreco** [comment]
clicking on a row is only supposed to zoom you in on the map, not open the popup, they are not tied together.
