### ISSUE TITLE
Remove commas after each search status

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#2]
Currently there is a comma after Permit Finaled, Permit Issued, In Review, etc. 
Drop down menu options do not have a comma after each option. The comma should be removed.

Also, is 'Finaled' the appropriate word? It just sounds grammatically incorrect. (But I could be wrong.)
![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21645430/edc79c34-d25f-11e6-93f7-1c06b76b8d6a.png)

**Comment by justingreco** [comment]
This is how the Angular Material component is suppose to look, dont think there is much we can do about this.
