### ISSUE TITLE
The test 'Status' is duplicated

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#3]
Follow these steps:
1. Under the 'Status' option select each of the four options available.
2. Then deselect each of the four options available
3. Select the <ESC> key or click on the page so that the drop down menu is no longer displayed
4. The test 'Status' is superimposed over the text 'Status' (see attached)
![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21646099/c9cd7620-d262-11e6-8586-578ee5b21b0d.png)

**Comment by justingreco** [comment]
believe this is an IE 10 issue, try in a newer browser.

**Comment by chavisa** [comment]
Duplicate shows in IE, FF and Chrome

**Comment by justingreco** [comment]
Please verify if you are still seeing this?  I cannot replicate it on my side.

**Comment by chavisa** [comment]
I am still seeing it, but it does not affect functionality.
