### ISSUE TITLE
The application is slower and has buffering using IE10

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#4]
When I view the application using IE10 it is slower and has frequent buffering; more so than using Chrome or Firefox.

The concern is that I have a fairly fast connection and computer, so if I can getting slow response using IE, then if a user's PC does not have high speed connection or a faster computer the problem would be even greater. 

Perhaps there should be a notification that the application works best with Chrome or Firefox.

**Comment by justingreco** [comment]
Only supported in IE11 and above, notification has been added for users with IE10 or below.  Older browsers do not support MapBox GL library.
