### ISSUE TITLE
VisualeEnhancement  of the menu options

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#8]
Currently the menus on the left side are rather cluttered and have a kind of 'run-on' appearance. The sections need to be segmented and separated with a border for user friendliness. See attached.

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21656405/02dd9af2-d28c-11e6-9189-e349d8217cba.png)

**Comment by justingreco** [comment]
This has been reformated to help separate different sections of the search.
