### ISSUE TITLE
Search function needs clarification

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/development-dashboard#9]
Underneath the map there is a toggle that when selected displays Search. The Search functions needs the following:
1. Some clarification as to the Search purpose and usage; for example, 'Search - Use this search feature to locate and display specific data details'. 
2. Currently, if search parameters are enter that cannot be found, the data simply disappears. Recommend that the data continue to be displayed along with a message, 'Search data not found'.
3. Currently the Search field allows unlimited data to be entered. Recommend a limit be put in place. 
4. Search does not clear when 'X' is selected. If I do a search on 'Bozo', no data is displayed (which is correct). I now want get rid of 'Bozo' and do another search, so I select 'X'. That does not clear 'Bozo' from the search field. I have to manually deleted 'Bozo from the search field. Recommend that selecting X clears the Search field and  remove all search parameters.

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/21657412/19e9b5f6-d290-11e6-8a2d-f3ffb9030556.png)

**Comment by justingreco** [comment]
Believe this is something they wanted removed, will need to check our notes.

**Comment by justingreco** [comment]
This functionality has been removed
